services:
    eduart-node-red:
        user: root
        image: eduartrobotik/eduart-nodered:0.2.1
        network_mode: host
        command: node-red --userDir /data
        restart: always
        privileged: true
        ipc: host
        pid: host
        volumes:
            - node_red_user_data:/data

volumes:
    node_red_user_data: