services:
    visual-ros:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
                ROS_DISTRO: humble
        network_mode: host
        command: node /usr/bin/node-red
