services:
    eduart-node-red:
        user: root
        # build:
        #     context: ..
        #     dockerfile: docker/Dockerfile
        #     args:
        #         ROS_DISTRO: humble
        image: eduart-nodered:0.2.0
        network_mode: host
        command: node-red
        restart: always
        privileged: true
        ipc: host
        pid: host
