services:
    eduart-node-red:
        user: root
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
                ROS_DISTRO: humble
        network_mode: host
        command: node-red
