name: Docker Compose Build and Push Workflow

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3    

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ghcr.io/user/app:latest
          ghcr.io/user/app:${{ env.sha_tag }}
          ghcr.io/user/app:${{ env.branch_tag }}
        file: docker/image/Dockerfile